---
# tasks file for lighthouse-role
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Create Nginx config
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify: Start nginx service

- name: Install git
  become: true
  ansible.builtin.apt:
    name: git
    state: present

- name: Copy lighthouse rfom git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_dir }}"

- name: Create lighthouse config
  become: true
  ansible.builtin.template:
    src: templates/lighthouse.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload Nginx service
